export const themes = {
  bank: {
    title: "Bank",
    titleText: "Mit bankoverblik",
    icon: "ic:outline-monetization-on",
    primaryColor: "#5183eb",
    primaryHoverColor: "#426ec9",
    primaryGradient: "linear(to-tr, #4876ED, #233DC3)",
  },
  mail: {
    title: "Email",
    titleText: "Min indbakke",
    icon: "ic:outline-email",
    primaryColor: "#8f2b2b",
    primaryHoverColor: "#459145",
    primaryGradient: "linear(to-tr, #C65E5E, #8E1D1D)",
  },
  jobportal: {
    title: "Job Portal",
    titleText: "Job portal",
    icon: "mdi:briefcase-account-outline",
    primaryColor: "#298371",
    primaryHoverColor: "#226231",
    primaryGradient: "linear(to-tr, #16B0BA, #1CA76D)",
  },
  explore: {
    title: "Udforsk",
    titleText: "Udforsk",
    icon: "mdi:compass-outline",
    primaryColor: "#9146D1",
    primaryHoverColor: "#8f528f",
    primaryGradient: "linear(to-tr, #7348ED, #B443AF)",
  },
  newspaper: {
    title: "Avis",
    titleText: "Avis",
    icon: "ic:round-menu-book",
    primaryColor: "#9f6d06",
    primaryHoverColor: "#cbcb4f",
    primaryGradient: "linear(to-tr, #E09427, #D7AB29)",
  },
  profile: {
    title: "Profil",
    titleText: "Min profil",
    icon: "ic:baseline-account-circle",
    primaryColor: "#c3c3c3",
    primaryHoverColor: "#9d9d9d",
    primaryGradient: "linear(to-tr, #424D5E, #65707C)",
  },
};
